version: "3"

vars:
  BUILD_DIR: "../build"

tasks:
  setup:
    desc: Setup Docusaurus locally
    cmds:
      - npm install

  gen:
    desc: Generate CLI documentation
    dir: "{{.ROOT_DIR}}"
    cmds:
      - go run cmd/docs/main.go ./docs/pages/api.md

  start:
    desc: Start website
    aliases: [run]
    vars:
      PORT: '{{default "3001" .PORT}}'
    deps: [gen]
    cmds:
      - npx docusaurus start --no-open --port={{.PORT}}

  build:
    desc: Build website
    deps: [gen]
    cmds:
      - npx docusaurus build --out-dir {{.BUILD_DIR}}

  clean:
    desc: Clean temp directories
    cmds:
      - rm -rf {{.BUILD_DIR}}
