version: "3"

vars:
  BUILD_DIR: "../build"

tasks:
  setup:
    desc: Setup Docusaurus locally
    cmds:
      - npm install

  gen:
    desc: Generate CLI documentation
    dir: ../../
    cmds:
      - go run cmd/docs/main.go

  start:
    desc: Start website
    aliases: [run]
    vars:
      PORT: '{{ default "3001" .PORT }}'
    deps: [gen]
    cmds:
      - npx docusaurus start --no-open --port={{ .PORT }}
      - defer: { task: cleanup }

  build:
    desc: Build website
    deps: [gen]
    cmds:
      - npx docusaurus build --out-dir {{ .BUILD_DIR }}

  cleanup:
    desc: Clean up generated files and temp directories
    cmds:
      - rm -rf {{ .BUILD_DIR }}
      - git checkout HEAD -- docs/api.mdx docs/changelog.mdx
