Feature: Check origin of a file in project directory using "why" command

	Scenario: File generated by a recipe
		Given a project directory
		And a recipes directory
		And a recipe "foo" that generates file "README.md" with content "initial"
		And I execute recipe "foo"
		When I check why the file "README.md" is created
		Then CLI produced an output "File 'README.md' is created by the recipe 'foo'"

	Scenario: Nested file generated by a recipe
		Given a project directory
		And a recipes directory
		And a recipe "foo" that generates file "foo/bar.yml" with content "initial"
		And I execute recipe "foo"
		When I check why the file "foo/bar.yml" is created
		Then CLI produced an output "File 'foo/bar.yml' is created by the recipe 'foo'"
	
	Scenario: Directory generated by a recipe
		Given a project directory
		And a recipes directory
		And a recipe "foo" that generates file "foo/bar.yml" with content "initial"
		And I execute recipe "foo"
		When I check why the file "foo" is created
		Then CLI produced an output "Directory 'foo' is created by the recipe 'foo'"

	Scenario: Directory generated by Jalapeno
		Given a project directory
		And a recipes directory
		And a recipe "foo" that generates file "README.md" with content "initial"
		And I execute recipe "foo"
		When I check why the file ".jalapeno" is created
		Then CLI produced an output "Directory '.jalapeno' is created by Jalapeno"
	
	Scenario: File generated by Jalapeno
		Given a project directory
		And a recipes directory
		And a recipe "foo" that generates file "README.md" with content "initial"
		And I execute recipe "foo"
		When I check why the file ".jalapeno/sauces.yml" is created
		Then CLI produced an output "File '.jalapeno/sauces.yml' is created by Jalapeno"

	Scenario: File not found
		Given a project directory
		And a recipes directory
		And a recipe "foo" that generates file "README.md" with content "initial"
		And I execute recipe "foo"
		When I check why the file "not-found" is created
		Then CLI produced an error "file '.*/not-found' does not exist"
