apiVersion: v1
name: github-action
version: v0.0.0
description: A GitHub Action that checks updates for Jalapeno recipes in the project periodically
vars:
  - name: SCHEDULE
    description: Cron expression to determine when the updates should be checked. Defaults to every Monday at 12:00 UTC
    default: 0 12 * * 1
    validators:
      - pattern: ^(\*|([0-9]|1[0-9]|2[0-9]|3[0-9]|4[0-9]|5[0-9])|\*\/([0-9]|1[0-9]|2[0-9]|3[0-9]|4[0-9]|5[0-9])) (\*|([0-9]|1[0-9]|2[0-3])|\*\/([0-9]|1[0-9]|2[0-3])) (\*|([1-9]|1[0-9]|2[0-9]|3[0-1])|\*\/([1-9]|1[0-9]|2[0-9]|3[0-1])) (\*|([1-9]|1[0-2])|\*\/([1-9]|1[0-2])) (\*|([0-6])|\*\/([0-6]))$
        help: Must be a valid cron expression
