builds:
  - id: jalapeno
    dir: cmd/jalapeno
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

kos:
  - repository: ghcr.io/futurice/jalapeno
    base_image: alpine
    tags:
      - latest
      - "v{{.Version}}"
      - "v{{.Major}}"
      - "v{{.Major}}.{{.Minor}}"
    sbom: none
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.authors: "Jalapeno contributors <github.com/futurice/jalapeno>"
      org.opencontainers.image.licenses: "Apache-2.0"
      org.opencontainers.image.vendor: "Futurice"
      org.opencontainers.image.title: "Jalapeno"
      org.opencontainers.image.description: "Jalapeno is a CLI for creating, managing and sharing spiced up project templates."
      org.opencontainers.image.url: "https://github.com/futurice/jalapeno"
      org.opencontainers.image.source: "https://github.com/futurice/jalapeno"
      org.opencontainers.image.documentation: "https://futurice.github.io/jalapeno/"

archives:
  - id: jalapeno
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: jalapeno
    # GitHub repository
    repository:
      owner: futurice
      name: homebrew-jalapeno
      git:
        url: "git@github.com:futurice/homebrew-jalapeno.git"
        private_key: "{{ .Env.HOMEBREW_TAP_PRIVATE_KEY }}"
    # metadata
    homepage: "https://futurice.github.io/jalapeno/"
    description: "Jalapeno is a CLI for creating, managing and sharing spiced up project templates"
    license: "Apache-2.0"
    # how release is being downloaded/used
    download_strategy: CurlDownloadStrategy
    # actual formula things
    commit_msg_template: "Brew formula update for jalapeno version {{ .Tag }}"
    test: |
      system "#{bin}/jalapeno --version"

winget:
- name: jalapeno
  publisher: Futurice
  publisher_url: https://www.futurice.com
  publisher_support_url: https://github.com/futurice/jalapeno/issues/new
  short_description: Jalapeno is a CLI for creating, managing and sharing spiced up project templates
  license: "Apache-2.0"
  homepage: https://futurice.github.io/jalapeno/
  license_url: https://github.com/futurice/jalapeno/blob/main/LICENCE
  release_notes: '{{ .Changelog }}'
  release_notes_url: 'https://github.com/futurice/jalapeno/releases/tag/{{ .Tag }}'
  tags:
  - cli
  - configuration
  - project
  - bootstrap
  - templates
  repository:
    owner: futurice
    name: winget-pkgs
    branch: "{{.ProjectName}}-{{.Version}}"
    git:
      url: "git@github.com:futurice/winget-pkgs.git"
      private_key: "{{ .Env.WINGET_PKGS_PRIVATE_KEY }}"
    pull_request:
      enabled: true
      base:
        owner: microsoft
        name: winget-pkgs
        branch: master
