version: 2

builds:
  - id: jalapeno
    dir: cmd/jalapeno
    env:
      - CGO_ENABLED=0
    ldflags: &ldflags
      - -s -w
      - -X github.com/futurice/jalapeno/internal/cli.version={{.Version}}
      - -X github.com/futurice/jalapeno/internal/cli/option.version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: github-action
    dir: cmd/action
    env:
      - CGO_ENABLED=0
    ldflags: *ldflags
    goos:
      - linux
    goarch:
      - amd64
      - arm64

kos:
  - id: jalapeno
    repositories:
      - ghcr.io/futurice/jalapeno
    build: jalapeno
    base_image: alpine
    tags:
      - latest
      - "v{{.Major}}"
      - "v{{.Major}}.{{.Minor}}"
      - "v{{.Version}}"
    sbom: none
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
    labels: &labels
      org.opencontainers.image.authors: "Jalapeno contributors <github.com/futurice/jalapeno>"
      org.opencontainers.image.licenses: "Apache-2.0"
      org.opencontainers.image.vendor: "Futurice"
      org.opencontainers.image.title: "Jalapeno"
      org.opencontainers.image.version: "v{{.Version}}"
      org.opencontainers.image.description: "Jalapeno is a CLI for creating, managing and sharing spiced up project templates."
      org.opencontainers.image.url: "https://github.com/futurice/jalapeno"
      org.opencontainers.image.source: "https://github.com/futurice/jalapeno"
      org.opencontainers.image.documentation: "https://futurice.github.io/jalapeno/"
  - id: github-action
    repositories:
      - ghcr.io/futurice/jalapeno
    build: github-action
    base_image: alpine
    tags:
      - "latest-githubaction"
      - "v{{.Major}}-githubaction"
      - "v{{.Major}}.{{.Minor}}-githubaction"
      - "v{{.Version}}-githubaction"
    sbom: none
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
    labels: *labels

archives:
  - id: jalapeno
    ids: [jalapeno]
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

homebrew_casks:
  - name: jalapeno
    repository:
      owner: futurice
      name: homebrew-jalapeno
      branch: main
      git:
        url: "git@github.com:futurice/homebrew-jalapeno.git"
        private_key: "{{ .Env.HOMEBREW_TAP_PRIVATE_KEY }}"
    conflicts:
      - formula: jalapeno # https://goreleaser.com/deprecations/#brews
    homepage: "https://futurice.github.io/jalapeno/"
    description: "Jalapeno is a CLI for creating, managing and sharing spiced up project templates"
    license: "Apache-2.0"
    commit_msg_template: "Brew formula update for jalapeno version {{ .Tag }}"
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jalapeno"]
          end

winget:
  - name: jalapeno
    publisher: Futurice
    publisher_url: https://www.futurice.com
    publisher_support_url: https://github.com/futurice/jalapeno/issues/new
    short_description: Jalapeno is a CLI for creating, managing and sharing spiced up project templates
    license: "Apache-2.0"
    homepage: https://futurice.github.io/jalapeno/
    license_url: https://github.com/futurice/jalapeno/blob/main/LICENCE
    release_notes: "{{ .Changelog }}"
    release_notes_url: "https://github.com/futurice/jalapeno/releases/tag/{{ .Tag }}"
    tags:
      - cli
      - configuration
      - project
      - bootstrap
      - templates
    repository:
      owner: futurice
      name: winget-pkgs
      branch: "{{.ProjectName}}-{{.Version}}"
      git:
        url: "git@github.com:futurice/winget-pkgs.git"
        private_key: "{{ .Env.WINGET_PKGS_PRIVATE_KEY }}"
      pull_request:
        enabled: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

announce:
  slack:
    enabled: true
    message_template: "Jalapeno {{.Tag}} is out! Check the release notes at {{ .ReleaseURL }}"
    channel: "#jalapeno"
