name: "Jalapeno"
description: "Run Jalapeno check on the workspace"
runs:
  using: "docker"
  image: "docker://ghcr.io/futurice/jalapeno:v0-githubaction"
  args:
    - check
    - --dir=/github/workspace
