name: "Jalapeno"
description: "Run arbitrary Jalapeno commands"
inputs:
  cmd:
    description: "The command which should be run"
    required: true
outputs:
  result:
    description: "stdout after running the command"
  exitcode:
    description: "Exit code of the operation"
runs:
  using: "docker"
  image: "docker://ghcr.io/futurice/jalapeno:v1-githubaction"
  args:
    - ${{ inputs.cmd }}
