version: "3"

includes:
  docs:
    taskfile: ./docs
    dir: ./docs

tasks:
  mod:
    desc: Downloads and tidy Go modules
    cmds:
      - go mod download
      - go mod tidy
  lint:
    desc: Runs golangci-lint
    sources:
      - "./**/*.go"
    cmds:
      - golangci-lint run
  run:
    cmds:
      - go run ./cmd {{.CLI_ARGS}}
  build:
    desc: Build the CLI
    sources:
      - "./**/*.go"
    cmds:
      - go build -o bin/jalapeno ./cmd
  debug:
    desc: Starts the CLI in debug mode. After running the task, you can use for example VSCode to connect to the session
    cmds:
      - >-
        $(go env GOPATH)/bin/dlv debug ./cmd
        --headless
        --listen 127.0.0.1:52800
        --api-version 2
        -- {{.CLI_ARGS}}
  test:
    cmds:
      - go test ./...
