version: "3"

includes:
  docs:
    taskfile: ./docs/site
    dir: ./docs/site

vars:
  ENTRYPOINT: "{{.TASKFILE_DIR}}/cmd/jalapeno" # Path to main package

tasks:
  lint:
    desc: Runs linters
    sources:
      - "./**/*.go"
    cmds:
      - golangci-lint run

  run:
    desc: "Run a CLI command with arguments. Example: `task run -- execute ./my-recipe`"
    cmds:
      - go run {{.ENTRYPOINT}} {{.CLI_ARGS}}

  build:
    desc: Build the CLI
    sources:
      - "./**/*.go"
    generates:
      - "bin/jalapeno{{exeExt}}"
    cmds:
      - go build -o bin/jalapeno{{exeExt}} {{.ENTRYPOINT}}

  debug:
    desc: Starts the CLI in debug mode. After running the task, you can use for example VSCode to connect to the session
    cmds:
      - >-
        $(go env GOPATH)/bin/dlv debug {{.ENTRYPOINT}}
        --headless
        --listen 127.0.0.1:52800
        --api-version 2
        -- {{.CLI_ARGS}}

  test:
    desc: Run the test suite
    cmds:
      - task: lint
      - go test {{.CLI_ARGS}} ./...
