apiVersion: v1
name: table-variable
description: |
  This recipe demonstrates how to use table variables.

  You can also pre-set the table variable by using CSV with having '\n' between the rows, for example:
  `jalapeno execute examples/table-variable `--set 'ENVIRONMENTS=dev;app-dev;1\nqa;app-qa;1\nprod;app-prod;5'`
version: v0.0.0
vars:
  - name: ENVIRONMENTS
    columns: [name, app, scale]
  - name: CONDITIONAL
    description: Conditional variable which depends on one value in the table
    confirm: true
    if: ENVIRONMENTS[0].name == "dev"
