package recipe

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	defaultFileMode  os.FileMode = 0700
	yamlIndent       int         = 2
	sauceFileComment string      = "# This file is generated by Jalapeno (https://futurice.github.io/jalapeno)\n"
)

func ValidatePath(basePath, filePath string) error {
	absBasePath, err := filepath.Abs(basePath)
	if err != nil {
		return fmt.Errorf("invalid base path %q: %v", basePath, err)
	}

	absFilePath, err := filepath.Abs(filePath)
	if err != nil {
		return fmt.Errorf("invalid file path %q: %v", basePath, err)
	}

	if !strings.HasPrefix(absFilePath, absBasePath) {
		return fmt.Errorf("file path escapes destination: %q outside %q", absFilePath, absBasePath)
	}

	return nil
}

// Save saves recipe to given destination
func (re *Recipe) Save(dest string) error {
	if err := re.Validate(); err != nil {
		return fmt.Errorf("can not save the recipe since it is not valid: %w", err)
	}

	err := os.MkdirAll(dest, defaultFileMode)
	if err != nil {
		return fmt.Errorf("can not create directory %s: %v", dest, err)
	}

	recipeFilepath := filepath.Join(dest, MetadataFileName+YAMLExtension)
	file, err := os.Create(recipeFilepath)
	if err != nil {
		return fmt.Errorf("failed to create recipe file: %w", err)
	}

	encoder := yaml.NewEncoder(file)
	encoder.SetIndent(yamlIndent)
	if err := encoder.Encode(re); err != nil {
		return fmt.Errorf("failed to write recipe to a file: %w", err)
	}

	if err := encoder.Close(); err != nil {
		return fmt.Errorf("failed to close recipe YAML encoder: %w", err)
	}
	if err := file.Close(); err != nil {
		return fmt.Errorf("failed to close recipe file: %w", err)
	}

	err = re.saveTemplates(dest)
	if err != nil {
		return fmt.Errorf("can not save recipe templates: %w", err)
	}

	err = re.saveTests(dest)
	if err != nil {
		return fmt.Errorf("can not save recipe tests: %w", err)
	}

	return nil
}

func (re *Recipe) saveTests(dest string) error {
	if len(re.Tests) == 0 {
		return nil
	}

	testRootDir := filepath.Join(dest, TestsDirName)

	err := os.MkdirAll(testRootDir, defaultFileMode)
	if err != nil {
		return fmt.Errorf("can not create recipe test directory: %w", err)
	}

	for _, test := range re.Tests {
		testDirPath := filepath.Join(testRootDir, test.Name)
		err := os.MkdirAll(filepath.Join(testRootDir, test.Name), defaultFileMode)
		if err != nil {
			return fmt.Errorf("failed to create test directory for test '%s': %w", test.Name, err)
		}

		meta, err := os.Create(filepath.Join(testDirPath, TestMetaFileName+YAMLExtension))
		if err != nil {
			return fmt.Errorf("failed to create recipe test file: %w", err)
		}
		defer meta.Close()

		encoder := yaml.NewEncoder(meta)
		encoder.SetIndent(yamlIndent)
		defer encoder.Close()

		if err := encoder.Encode(test); err != nil {
			return fmt.Errorf("failed to write recipe test to a file: %w", err)
		}

		testFileDirPath := filepath.Join(testDirPath, TestFilesDirName)
		err = os.RemoveAll(testFileDirPath)
		if err != nil {
			return fmt.Errorf("failed to clean up test file directory for test '%s': %w", test.Name, err)
		}

		err = os.MkdirAll(testFileDirPath, defaultFileMode)
		if err != nil {
			return fmt.Errorf("failed to create test file directory for test '%s': %w", test.Name, err)
		}

		if len(test.Files) > 0 {
			err = saveFileMap(test.Files, testFileDirPath)
			if err != nil {
				return fmt.Errorf("failed to save template files: %w", err)
			}
		}
	}

	return nil
}

func (re *Recipe) saveTemplates(dest string) error {
	templateDir := filepath.Join(dest, TemplatesDirName)
	err := os.MkdirAll(templateDir, defaultFileMode)
	if err != nil {
		return fmt.Errorf("can not save templates to the directory: %w", err)
	}

	err = saveFileMap(re.Templates, templateDir)
	if err != nil {
		return fmt.Errorf("failed to save template files: %w", err)
	}

	return nil
}

// Save saves sauce to given destination
func (s *Sauce) Save(dest string) error {
	if err := s.Validate(); err != nil {
		return fmt.Errorf("can not save the sauce since it is not valid: %w", err)
	}

	// load all sauces from target dir, because we will either replace
	// a previous sauce, or create a new file
	sauces, err := LoadSauces(dest)
	if err != nil {
		return err
	}
	added := false
	for i, prev := range sauces {
		if s.ID == prev.ID {
			// found by ID
			sauces[i] = s
			added = true
			break
		}
	}
	if !added {
		// we hit the end, append
		sauces = append(sauces, s)
	}

	if err := os.MkdirAll(filepath.Join(dest, SauceDirName), defaultFileMode); err != nil {
		return fmt.Errorf("failed to create sauce dir: %w", err)
	}
	file, err := os.Create(filepath.Join(dest, SauceDirName, SaucesFileName+YAMLExtension))
	if err != nil {
		return fmt.Errorf("failed to create sauce file: %w", err)
	}
	defer file.Close()

	_, err = file.WriteString(sauceFileComment)
	if err != nil {
		return fmt.Errorf("failed to write comment a the sauce file: %w", err)
	}

	encoder := yaml.NewEncoder(file)
	encoder.SetIndent(yamlIndent)
	defer encoder.Close()

	for _, sauce := range sauces {
		if err := encoder.Encode(sauce); err != nil {
			return fmt.Errorf("failed to write sauces: %w", err)
		}
	}

	fileMap := make(map[string][]byte)
	for filename, file := range s.Files {
		fileMap[filename] = file.Content
	}

	if s.Subpath != "" {
		dest = filepath.Join(dest, s.Subpath)
	}

	err = saveFileMap(s.Files, dest)
	if err != nil {
		return fmt.Errorf("failed to save sauce files: %w", err)
	}

	return nil
}

func saveFileMap(files map[string]File, dest string) error {
	if len(files) == 0 {
		return nil
	}

	err := os.MkdirAll(filepath.Dir(dest), 0700)
	if err != nil {
		return fmt.Errorf("failed to create destination directory for files: %w", err)
	}

	for path, file := range files {
		destPath := filepath.Join(dest, path)

		err := ValidatePath(dest, destPath)
		if err != nil {
			return err
		}

		// Create file's parent directories (if not already exist)
		err = os.MkdirAll(filepath.Dir(destPath), 0700)
		if err != nil {
			return err
		}

		// Create the file
		f, err := os.Create(destPath)
		if err != nil {
			return err
		}
		defer f.Close()

		// Write the data to the file
		_, err = f.Write(file.Content)
		if err != nil {
			return err
		}

		err = f.Sync()
		if err != nil {
			return err
		}
	}
	return nil
}

func (m *Manifest) Save(path string) error {
	file, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("failed to create manifest file: %w", err)
	}

	encoder := yaml.NewEncoder(file)
	encoder.SetIndent(yamlIndent)
	if err := encoder.Encode(m); err != nil {
		return fmt.Errorf("failed to write manifest to a file: %w", err)
	}

	if err := encoder.Close(); err != nil {
		return fmt.Errorf("failed to close manifest YAML encoder: %w", err)
	}
	if err := file.Close(); err != nil {
		return fmt.Errorf("failed to close manifest file: %w", err)
	}

	return nil
}
