name: Lint

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Lint source code
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
