name: Lint

on:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - uses: actions/checkout@v3

      - name: Lint source code
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
