name: Publish recipe examples

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/publish-examples.yml"
      - "examples/**"

jobs:
  publish:
    name: Publish example recipes
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      DOCKER_CONFIG: $HOME/.docker
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # TODO: Loop over dynamically through all examples
      - uses: futurice/jalapeno@main
        with:
          cmd: push ./examples/github-action oci://ghcr.io/futurice/jalapeno/examples/github-action
      - uses: futurice/jalapeno@main
        with:
          cmd: push ./examples/minimal oci://ghcr.io/futurice/jalapeno/examples/minimal
      - uses: futurice/jalapeno@main
        with:
          cmd: push ./examples/variable-types oci://ghcr.io/futurice/jalapeno/examples/variable-types
      - uses: futurice/jalapeno@main
        with:
          cmd: push ./examples/with-tests oci://ghcr.io/futurice/jalapeno/examples/with-tests
      - uses: futurice/jalapeno@main
        with:
          cmd: push ./examples/terraform-bootstrap oci://ghcr.io/futurice/jalapeno/examples/terraform-bootstrap
